package br.com.finan.form.despesa;

import java.lang.reflect.InvocationTargetException;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import org.apache.commons.beanutils.BeanUtils;
import br.com.finan.entidade.Categoria;
import br.com.finan.entidade.Conta;
import br.com.finan.entidade.enumerator.FormaPagamento;
import br.com.finan.entidade.enumerator.Frequencia;
import br.com.finan.entidade.enumerator.TipoConta;
import br.com.finan.form.principal.CadastroForm;
import br.com.finan.util.CalcularRecorrencia;
import br.com.finan.util.HibernateUtil;

/**
 *
 * @author Wesley Luiz
 */
public class CadastroDespesaForm extends CadastroForm<Conta> {

	/** Atributo serialVersionUID. */
	private static final long serialVersionUID = 1L;
	private int limite = 1;
	private Frequencia recorrencia;
	private FormaPagamento formaPagamento;

	/**
	 * Creates new form DespesaForm
	 */
	public CadastroDespesaForm() {
		initComponents();
		iniciarDados();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

		panelCadastro = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		textDescricao = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		btnSalvar = new javax.swing.JButton();
		txtVencimento = new javax.swing.JFormattedTextField(getFormatters().getDateFormatter());
		txtValor = new br.com.finan.component.JMoneyField();
		txtCategoria = new javax.swing.JComboBox();
		jLabel5 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		txtObservacoes = new javax.swing.JTextArea();
		jLabel1 = new javax.swing.JLabel();
		txtPago = new javax.swing.JCheckBox();
		jLabel6 = new javax.swing.JLabel();
		txtPagamento = new javax.swing.JFormattedTextField(getFormatters().getDateFormatter());
		jLabel7 = new javax.swing.JLabel();
		txtContaBancaria = new javax.swing.JComboBox();
		jLabel8 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		txtRecorrencia = new javax.swing.JComboBox();
		txtLimite = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		btnFechar = new javax.swing.JButton();
		jLabel11 = new javax.swing.JLabel();
		txtFormaPagamento = new javax.swing.JComboBox();

		setClosable(true);
		setMaximizable(true);
		setResizable(true);

		panelCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel2.setText("Descrição:");

		org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${entidade.descricao}"), textDescricao,
				org.jdesktop.beansbinding.BeanProperty.create("text"));
		bindingGroup.addBinding(binding);

		jLabel3.setText("Vencimento:");

		jLabel4.setText("Valor:");

		btnSalvar.setText("Salvar");
		btnSalvar.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(final java.awt.event.ActionEvent evt) {
				btnSalvarActionPerformed(evt);
			}
		});

		binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${entidade.dataVencimento}"), txtVencimento, org.jdesktop.beansbinding.BeanProperty.create("value"));
		binding.setConverter(new br.com.finan.converter.DateConverter());
		bindingGroup.addBinding(binding);

		txtValor.setHorizontalAlignment(SwingConstants.LEADING);

		binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${entidade.valor}"), txtValor, org.jdesktop.beansbinding.BeanProperty.create("text"));
		binding.setConverter(new br.com.finan.converter.BigDecimalConverter());
		bindingGroup.addBinding(binding);

		binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${entidade.categoria}"), txtCategoria, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
		bindingGroup.addBinding(binding);

		jLabel5.setText("Categoria:");

		txtObservacoes.setColumns(20);
		txtObservacoes.setRows(5);

		binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${entidade.observacoes}"), txtObservacoes, org.jdesktop.beansbinding.BeanProperty.create("text"));
		bindingGroup.addBinding(binding);

		jScrollPane1.setViewportView(txtObservacoes);

		jLabel1.setText("Observações:");

		txtPago.setText("Sim");

		binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${entidade.isPago}"), txtPago, org.jdesktop.beansbinding.BeanProperty.create("selected"));
		bindingGroup.addBinding(binding);

		txtPago.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(final java.awt.event.ActionEvent evt) {
				txtPagoActionPerformed(evt);
			}
		});

		jLabel6.setText("Data pagamento:");

		binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtPago, org.jdesktop.beansbinding.ELProperty.create("${selected}"), jLabel6, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
		bindingGroup.addBinding(binding);

		binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${entidade.dataPagamento}"), txtPagamento, org.jdesktop.beansbinding.BeanProperty.create("value"));
		binding.setConverter(new br.com.finan.converter.DateConverter());
		bindingGroup.addBinding(binding);
		binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtPago, org.jdesktop.beansbinding.ELProperty.create("${selected}"), txtPagamento, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
		bindingGroup.addBinding(binding);

		jLabel7.setText("Definir como pago:");

		binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${entidade.contaBancaria}"), txtContaBancaria, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
		bindingGroup.addBinding(binding);

		jLabel8.setText("Conta Bancária:");

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Replicar lançamento"));

		jLabel9.setText("Recorrência:");

		binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${recorrencia}"), txtRecorrencia, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
		bindingGroup.addBinding(binding);

		binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${limite}"), txtLimite, org.jdesktop.beansbinding.BeanProperty.create("text"));
		bindingGroup.addBinding(binding);

		jLabel10.setText("Limite:");

		final javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout
				.createSequentialGroup()
				.addContainerGap()
				.addGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel9).addComponent(txtRecorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel10)
						.addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(126, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel9).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(txtRecorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE).addComponent(jLabel10)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(22, 22, 22)));

		btnFechar.setText("Fechar");

		jLabel11.setText("Forma de Pagamento:");

		binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtPago, org.jdesktop.beansbinding.ELProperty.create("${selected}"), jLabel11, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
		bindingGroup.addBinding(binding);

		binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${formaPagamento}"), txtFormaPagamento, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
		bindingGroup.addBinding(binding);
		binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtPago, org.jdesktop.beansbinding.ELProperty.create("${selected}"), txtFormaPagamento, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
		bindingGroup.addBinding(binding);

		final javax.swing.GroupLayout panelCadastroLayout = new javax.swing.GroupLayout(panelCadastro);
		panelCadastro.setLayout(panelCadastroLayout);
		panelCadastroLayout.setHorizontalGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				panelCadastroLayout
				.createSequentialGroup()
				.addContainerGap()
				.addGroup(
						panelCadastroLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								panelCadastroLayout
								.createSequentialGroup()
								.addGroup(
										panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel4).addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(txtPago)
										.addComponent(jLabel7))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												panelCadastroLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														panelCadastroLayout
														.createSequentialGroup()
														.addGap(38, 38, 38)
														.addGroup(
																panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel6)
																.addComponent(txtPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(28, 28, 28)
																.addGroup(
																		panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel11)
																		.addComponent(txtFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel5)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
																		.addGroup(
																				panelCadastroLayout
																				.createSequentialGroup()
																				.addGroup(
																						panelCadastroLayout
																						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(jLabel2).addComponent(textDescricao)
																								.addGroup(panelCadastroLayout.createSequentialGroup().addComponent(btnSalvar).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(btnFechar)).addComponent(jLabel1)
																								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)).addComponent(jLabel8)
																								.addComponent(txtContaBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGroup(
																										panelCadastroLayout
																										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																										.addGroup(
																												panelCadastroLayout
																												.createSequentialGroup()
																												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																												.addGroup(
																														panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel3)
																														.addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																panelCadastroLayout.createSequentialGroup().addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
																																.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(66, 66, 66)))))));
		panelCadastroLayout.setVerticalGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				panelCadastroLayout
				.createSequentialGroup()
				.addContainerGap()
				.addGroup(
						panelCadastroLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(
								panelCadastroLayout
								.createSequentialGroup()
								.addGroup(
										panelCadastroLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(
												panelCadastroLayout.createSequentialGroup().addComponent(jLabel2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(textDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														panelCadastroLayout.createSequentialGroup().addComponent(jLabel3).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel4).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																panelCadastroLayout.createSequentialGroup().addComponent(jLabel5).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel6).addComponent(jLabel7).addComponent(jLabel11))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		panelCadastroLayout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(txtPago)
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(txtPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(txtFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addGroup(
																						panelCadastroLayout
																						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								panelCadastroLayout.createSequentialGroup().addComponent(jLabel8).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(txtContaBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel1)
																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
																								.addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(btnSalvar).addComponent(btnFechar)).addContainerGap()));

		final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addComponent(panelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(panelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()));

		bindingGroup.bind();

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnSalvarActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalvarActionPerformed
		salvar();
	}// GEN-LAST:event_btnSalvarActionPerformed

	private void txtPagoActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPagoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtPagoActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnFechar;
	private javax.swing.JButton btnSalvar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JPanel panelCadastro;
	private javax.swing.JTextField textDescricao;
	private javax.swing.JComboBox txtCategoria;
	private javax.swing.JComboBox txtContaBancaria;
	private javax.swing.JComboBox txtFormaPagamento;
	private javax.swing.JTextField txtLimite;
	private javax.swing.JTextArea txtObservacoes;
	private javax.swing.JFormattedTextField txtPagamento;
	private javax.swing.JCheckBox txtPago;
	private javax.swing.JComboBox txtRecorrencia;
	private br.com.finan.component.JMoneyField txtValor;
	private javax.swing.JFormattedTextField txtVencimento;
	private org.jdesktop.beansbinding.BindingGroup bindingGroup;

	// End of variables declaration//GEN-END:variables

	@Override
	protected JInternalFrame getFrame() {
		return this;
	}

	@Override
	protected JPanel getContainerCadastro() {
		return panelCadastro;
	}

	@Override
	public void salvar() {
		// salvarEntidadesDependentes();
		final List<Date> vencimentos = new CalcularRecorrencia(getRecorrencia(), getEntidade().getDataVencimento(), getLimite()).obterVencimentos();

		for (int i = 0; i < getLimite(); i++) {
			try {
				final Conta conta = new Conta();
				BeanUtils.copyProperties(conta, getEntidade());
				conta.setParcela(i + 1);
				conta.setTotalParcelas(getLimite());
				conta.setDataVencimento(vencimentos.get(i));
				HibernateUtil.salvar(conta);
			} catch (IllegalAccessException | InvocationTargetException ex) {
				Logger.getLogger(CadastroDespesaForm.class.getName()).log(Level.SEVERE, null, ex);
			}
		}

		iniciarDados();
	}

	@Override
	protected void iniciarDados() {
		popularComboCategoria();
		popularComboRecorrencia();
		popularComboFormaPagamento();
		getEntidade().setTipo(TipoConta.DESPESA);
	}

	private void popularComboFormaPagamento() {
		txtFormaPagamento.removeAllItems();
		for (final FormaPagamento pag : Arrays.asList(FormaPagamento.values())) {
			txtFormaPagamento.addItem(pag);
		}
	}

	private void popularComboRecorrencia() {
		txtRecorrencia.removeAllItems();
		for (final Frequencia freq : Arrays.asList(Frequencia.values())) {
			txtRecorrencia.addItem(freq);
		}
	}

	private void popularComboCategoria() {
		final List<Categoria> categorias = HibernateUtil.getCriteriaBuilder(Categoria.class).eqStatusAtivo().addProjection("id", "status", "nome").addAliasToBean(Categoria.class).list();

		txtCategoria.removeAllItems();

		for (final Categoria cat : categorias) {
			txtCategoria.addItem(cat);
		}
	}

	private void salvarEntidadesDependentes() {
		final Categoria categoria = getEntidade().getCategoria();

		if (isReferencia(categoria) && !isReferencia(categoria.getId())) {
			HibernateUtil.salvar(categoria);
		}
	}

	public int getLimite() {
		return limite;
	}

	public void setLimite(final int limite) {
		this.limite = limite;
	}

	public Frequencia getRecorrencia() {
		return recorrencia;
	}

	public void setRecorrencia(final Frequencia recorrencia) {
		this.recorrencia = recorrencia;
	}

	public FormaPagamento getFormaPagamento() {
		return formaPagamento;
	}

	public void setFormaPagamento(final FormaPagamento formaPagamento) {
		this.formaPagamento = formaPagamento;
	}

}
